# Generated by Django 4.2.6 on 2023-10-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_driver_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_reg',
            name='Zip',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
