# Generated by Django 4.2.6 on 2023-10-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_driver_reg_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_reg',
            name='State',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
