# Generated by Django 4.2.6 on 2023-10-17 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_user_registration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_registration',
            new_name='user_reg',
        ),
    ]
