# Generated by Django 4.2.6 on 2023-10-23 06:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_user_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='one_way',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('StartingL', models.CharField(max_length=30)),
                ('EndingL', models.CharField(max_length=30)),
                ('Phone', models.IntegerField()),
            ],
        ),
    ]
