# Generated by Django 4.2.6 on 2023-10-25 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_one_way'),
    ]

    operations = [
        migrations.CreateModel(
            name='round_trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartingL', models.CharField(max_length=30)),
                ('EndingL', models.CharField(max_length=30)),
                ('Phone', models.IntegerField()),
            ],
        ),
    ]
