# Generated by Django 4.2.6 on 2023-10-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_round_trip'),
    ]

    operations = [
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartingL', models.CharField(max_length=30)),
                ('Days', models.IntegerField()),
                ('Phone', models.IntegerField()),
            ],
        ),
    ]
