# Generated by Django 4.2.6 on 2023-10-25 05:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_one_way_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='one_way',
            name='Date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
