# Generated by Django 4.2.6 on 2023-10-26 04:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_one_way_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='one_way',
            name='Date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
