# Generated by Django 4.2.6 on 2023-10-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_admin_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_reg',
            name='Status',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
