# Generated by Django 4.2.6 on 2023-10-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_driver_reg_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver_reg',
            name='Status',
        ),
        migrations.AddField(
            model_name='driver_login',
            name='Status',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
