# Generated by Django 4.2.6 on 2023-10-31 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_remove_driver_reg_status_driver_login_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver_login',
            name='Status',
        ),
        migrations.AddField(
            model_name='driver_reg',
            name='Status',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
