# Generated by Django 4.2.6 on 2023-11-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_remove_driver_login_status_driver_reg_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_login',
            name='Status',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
