# Generated by Django 4.2.6 on 2023-11-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_driver_login_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='one_way',
            name='Type',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='Type',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round_trip',
            name='Type',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
