# Generated by Django 4.2.6 on 2023-11-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_drivertableshow'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivertableshow',
            name='Status',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
