# Generated by Django 4.2.6 on 2023-11-10 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_drivertableshow_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='Destination',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='Name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round_trip',
            name='Date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='round_trip',
            name='Name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
