# Generated by Django 4.2.6 on 2023-11-10 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_package_destination_package_name_round_trip_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='E_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='package',
            name='S_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
