# Generated by Django 4.2.6 on 2023-11-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_package_e_date_package_s_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivertableshow',
            name='Driver',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
