# Generated by Django 4.2.6 on 2023-11-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_drivertableshow_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_reg',
            name='DriverId',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
