# Generated by Django 4.2.6 on 2023-11-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_driver_reg_driverid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drivertableshow',
            old_name='Driver',
            new_name='DriverId',
        ),
        migrations.AddField(
            model_name='drivertableshow',
            name='UserId',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_reg',
            name='UserId',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
