# Generated by Django 4.2.6 on 2023-11-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_rename_driver_drivertableshow_driverid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=50)),
                ('Message', models.CharField(max_length=1000)),
            ],
        ),
    ]
