# Generated by Django 4.2.6 on 2023-11-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_customer_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivertableshow',
            name='Date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='one_way',
            name='Date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='package',
            name='E_date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='package',
            name='S_date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='round_trip',
            name='Date',
            field=models.CharField(max_length=30),
        ),
    ]
