# Generated by Django 4.2.6 on 2023-11-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_alter_drivertableshow_date_alter_one_way_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='Payment_status',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
